# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-07 08:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 7, 8, 53, 43, 124452, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
